---
 - name: update system
   yum:
     name: "*"
     state: latest
     skip_broken: yes

 - name: Check if a reboot is required
   command: needs-restarting -r
   register: reg_reboot_required
   ignore_errors: yes
   failed_when: false
   changed_when: reg_reboot_required.rc != 0
   notify:
     - Reboot server
